# Generated by Django 5.2.15 on 2026-06-04 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biohuertos', '0001_initial'),
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='cosechas/', verbose_name='Foto')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad disponible')),
                ('unidad', models.CharField(choices=[('kg', 'Kilogramos'), ('unidades', 'Unidades'), ('atados', 'Atados'), ('cajas', 'Cajas')], default='kg', max_length=20, verbose_name='Unidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio referencial (S/)')),
                ('fecha_cosecha', models.DateField(verbose_name='Fecha de cosecha')),
                ('contacto', models.CharField(max_length=200, verbose_name='Medio de contacto (teléfono/WhatsApp)')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado')], default='disponible', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biohuerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosechas', to='biohuertos.biohuerto', verbose_name='Biohuerto')),
                ('cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cosechas_publicadas', to='cultivos.cultivo', verbose_name='Cultivo')),
            ],
            options={
                'verbose_name': 'Cosecha Publicada',
                'verbose_name_plural': 'Cosechas Publicadas',
                'ordering': ['-created_at'],
            },
        ),
    ]
