# Generated by Django 5.2.15 on 2026-06-07 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosechas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('emoji', models.CharField(default='🌱', max_length=10, verbose_name='Emoji')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='cosecha',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cosechas', to='cosechas.categoriacosecha', verbose_name='Categoría'),
        ),
        migrations.CreateModel(
            name='TipoCosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='cosechas.categoriacosecha')),
            ],
            options={
                'verbose_name': 'Tipo de cosecha',
                'verbose_name_plural': 'Tipos de cosecha',
                'ordering': ['nombre'],
                'unique_together': {('categoria', 'slug')},
            },
        ),
    ]
