# Generated by Django 5.2.15 on 2026-06-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_latitud_user_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.JSONField(default=list, verbose_name='Roles'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('productor', 'Productor'), ('admin', 'Administrador')], default='cliente', max_length=20, verbose_name='Rol principal'),
        ),
    ]
