# Generated by Django 5.2.15 on 2026-06-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biohuerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('codigo', models.CharField(blank=True, max_length=50, verbose_name='Código')),
                ('ubicacion', models.TextField(verbose_name='Ubicación de referencia')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área (m²)')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción general')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Biohuerto',
                'verbose_name_plural': 'Biohuertos',
                'ordering': ['-created_at'],
            },
        ),
    ]
