# Generated by Django 5.2.15 on 2026-06-07 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biohuertos', '0004_biohuerto_departamento_provincia_distrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoBiohuerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('licencia', 'Licencia'), ('certificacion', 'Certificación'), ('permiso', 'Permiso'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='biohuertos/documentos/')),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('biohuerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='biohuertos.biohuerto')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
