# Generated by Django 5.2.15 on 2026-06-09 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biohuertos', '0005_documentobiohuerto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiohuertMiembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('operario', 'Operario')], default='operario', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('biohuerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='biohuertos.biohuerto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships_biohuerto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rol', 'usuario__first_name'],
                'unique_together': {('biohuerto', 'usuario')},
            },
        ),
    ]
