# Generated by Django 5.2.15 on 2026-06-04 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biohuertos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoreoRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del registro')),
                ('humedad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Humedad (%)')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura (°C)')),
                ('luminosidad', models.CharField(blank=True, choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=10, verbose_name='Luminosidad')),
                ('incidencias', models.TextField(blank=True, verbose_name='Incidencias o novedades del día')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('biohuerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoreos', to='biohuertos.biohuerto', verbose_name='Biohuerto')),
            ],
            options={
                'verbose_name': 'Registro de Monitoreo',
                'verbose_name_plural': 'Registros de Monitoreo',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
