# Generated by Django 5.2.15 on 2026-06-04 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parte_afectada', models.CharField(max_length=100, verbose_name='Parte afectada')),
                ('sintomas', models.JSONField(default=list, verbose_name='Síntomas seleccionados')),
                ('diagnostico_probable', models.CharField(max_length=300, verbose_name='Diagnóstico probable')),
                ('causa_probable', models.TextField(verbose_name='Causa probable')),
                ('recomendacion', models.TextField(verbose_name='Recomendación de manejo orgánico')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha del diagnóstico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='cultivos.cultivo', verbose_name='Cultivo')),
            ],
            options={
                'verbose_name': 'Diagnóstico Fitosanitario',
                'verbose_name_plural': 'Diagnósticos Fitosanitarios',
                'ordering': ['-fecha'],
            },
        ),
    ]
