# Generated by Django 5.2.15 on 2026-06-04 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biohuertos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del cultivo')),
                ('fecha_siembra', models.DateField(verbose_name='Fecha de siembra')),
                ('etapa', models.CharField(choices=[('germinacion', 'Germinación'), ('crecimiento', 'Crecimiento'), ('floracion', 'Floración'), ('cosecha', 'Cosecha')], default='germinacion', max_length=20, verbose_name='Etapa actual')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad / Área sembrada')),
                ('unidad', models.CharField(default='m²', max_length=50, verbose_name='Unidad')),
                ('fecha_estimada_cosecha', models.DateField(verbose_name='Fecha estimada de cosecha')),
                ('notas', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('cosechado', 'Cosechado'), ('perdido', 'Perdido')], default='activo', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biohuerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivos', to='biohuertos.biohuerto', verbose_name='Biohuerto')),
            ],
            options={
                'verbose_name': 'Cultivo',
                'verbose_name_plural': 'Cultivos',
                'ordering': ['-created_at'],
            },
        ),
    ]
