# Generated by Django 5.2.15 on 2026-06-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='tipo_ciclo',
            field=models.CharField(choices=[('anual', 'Anual'), ('perenne', 'Perenne')], default='anual', max_length=10, verbose_name='Tipo de ciclo'),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad / Área'),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='etapa',
            field=models.CharField(choices=[('germinacion', 'Germinación'), ('crecimiento', 'Crecimiento'), ('establecido', 'Establecido'), ('poda', 'Poda'), ('brotacion', 'Brotación'), ('floracion', 'Floración'), ('cosecha', 'Cosecha')], default='germinacion', max_length=20, verbose_name='Etapa actual'),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='fecha_estimada_cosecha',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima cosecha estimada'),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='fecha_siembra',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de siembra / plantación'),
        ),
    ]
