# Generated by Django 5.2.15 on 2026-06-07 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biohuertos', '0005_documentobiohuerto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoAgricola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('fitosanitario', 'Fitosanitario'), ('fertilizante', 'Fertilizante'), ('bioestimulante', 'Bioestimulante'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('unidad', models.CharField(default='L', max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto agrícola',
                'verbose_name_plural': 'Productos agrícolas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('formacion', 'Formación de planta'), ('poda', 'Poda'), ('riego', 'Riego'), ('aplicacion', 'Aplicación'), ('cosecha', 'Cosecha'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('unidad_default', models.CharField(default='hora', max_length=50)),
                ('costo_unitario_default', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de labor',
                'verbose_name_plural': 'Tipos de labor',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivo', models.CharField(max_length=100, verbose_name='Cultivo macro')),
                ('nombre', models.CharField(max_length=100, verbose_name='Variedad')),
                ('subtipo', models.CharField(blank=True, max_length=100, verbose_name='Subtipo')),
                ('tipo_ciclo', models.CharField(choices=[('anual', 'Anual'), ('perenne', 'Perenne')], default='anual', max_length=10)),
                ('dias_ciclo', models.IntegerField(blank=True, null=True, verbose_name='Días estimados por ciclo')),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Variedades',
                'ordering': ['cultivo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30)),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_area', models.CharField(default='m²', max_length=10)),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('activa', 'Activa'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='planificada', max_length=15)),
                ('objetivo_cosecha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidad_cosecha', models.CharField(blank=True, max_length=50)),
                ('precio_venta_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biohuerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanas', to='biohuertos.biohuerto')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campanas', to='campanas.variedad')),
            ],
            options={
                'ordering': ['-anio', '-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PracticaSostenible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('compost', 'Uso de compost'), ('sin_agroquimicos', 'Sin agroquímicos sintéticos'), ('riego_eficiente', 'Riego eficiente'), ('control_biologico', 'Control biológico'), ('abono_verde', 'Abono verde'), ('otro', 'Otra práctica')], default='otro', max_length=25)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidad', models.CharField(blank=True, max_length=50)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas_sostenibles', to='campanas.campana')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PresupuestoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('insumo', 'Insumo / Producto'), ('agua', 'Agua'), ('mano_obra', 'Mano de obra'), ('otro', 'Otro')], default='insumo', max_length=15)),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(max_length=50)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_ejecutado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto', to='campanas.campana')),
            ],
            options={
                'ordering': ['categoria', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='PlanRiego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('metodo', models.CharField(choices=[('goteo', 'Goteo'), ('aspersion', 'Aspersión'), ('gravedad', 'Gravedad'), ('manual', 'Manual')], default='goteo', max_length=15)),
                ('litros_por_m2', models.DecimalField(decimal_places=2, max_digits=8)),
                ('frecuencia_dias', models.IntegerField()),
                ('duracion_minutos', models.IntegerField(blank=True, null=True)),
                ('dosis_fertilizante', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_riego', to='campanas.campana')),
                ('fertilizante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_riego', to='campanas.productoagricola')),
            ],
            options={
                'ordering': ['fecha_inicio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ItemFitosanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(max_length=200, verbose_name='Objetivo / plaga-enfermedad')),
                ('dosis', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unidad', models.CharField(default='L/ha', max_length=20)),
                ('dias_antes_cosecha', models.IntegerField(blank=True, null=True, verbose_name='Intervalo seguridad (días antes cosecha)')),
                ('condicion', models.CharField(blank=True, max_length=200, verbose_name='Condición de aplicación')),
                ('frecuencia_dias', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_fitosanitario', to='campanas.campana')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campanas.productoagricola')),
            ],
            options={
                'ordering': ['fecha_inicio', 'producto__nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('dosis_aplicada', models.DecimalField(decimal_places=3, max_digits=10)),
                ('area_aplicada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('operario', models.CharField(blank=True, max_length=100)),
                ('es_sostenible', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='campanas.campana')),
                ('item_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campanas.itemfitosanitario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campanas.productoagricola')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RegistroRiego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('litros_aplicados', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_regada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_agua', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dosis_fertilizante', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('operario', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_riego', to='campanas.campana')),
                ('fertilizante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_riego', to='campanas.productoagricola')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campanas.planriego')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='LaborCampana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha_programada', models.DateField()),
                ('fecha_ejecutada', models.DateField(blank=True, null=True)),
                ('cantidad_programada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_ejecutada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('operario', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('ejecutada', 'Ejecutada'), ('cancelada', 'Cancelada')], default='programada', max_length=15)),
                ('notas', models.TextField(blank=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labores', to='campanas.campana')),
                ('tipo_labor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campanas.tipolabor')),
            ],
            options={
                'ordering': ['fecha_programada'],
            },
        ),
    ]
