# Generated by Django 5.2.15 on 2026-06-07 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('semana_relativa', models.IntegerField(blank=True, null=True, verbose_name='Semana del ciclo')),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('tipo_labor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campanas.tipolabor')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantilla_labores', to='campanas.variedad')),
            ],
            options={
                'ordering': ['semana_relativa', 'tipo_labor__nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(blank=True, max_length=200)),
                ('dosis', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('unidad', models.CharField(default='L/ha', max_length=20)),
                ('dias_antes_cosecha', models.IntegerField(blank=True, null=True)),
                ('frecuencia_dias', models.IntegerField(blank=True, null=True)),
                ('condicion', models.CharField(blank=True, max_length=200)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campanas.productoagricola')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantilla_productos', to='campanas.variedad')),
            ],
            options={
                'ordering': ['producto__nombre'],
            },
        ),
    ]
