# Generated by Django 5.2.15 on 2026-06-07 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanas', '0002_plantillalabor_plantillaproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('tipo', models.CharField(choices=[('control', 'Control fitosanitario'), ('prevencion', 'Prevención'), ('fertilizacion', 'Fertilización'), ('estimulacion', 'Bioestimulación'), ('otro', 'Otro')], default='control', max_length=20)),
            ],
            options={
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Plaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nombre_cientifico', models.CharField(blank=True, max_length=150)),
                ('tipo', models.CharField(choices=[('insecto', 'Insecto'), ('acaro', 'Ácaro'), ('hongo', 'Hongo'), ('bacteria', 'Bacteria'), ('virus', 'Virus'), ('nematodo', 'Nematodo'), ('maleza', 'Maleza'), ('otro', 'Otro')], default='otro', max_length=15)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('tipo', models.CharField(choices=[('vol_area', 'Volumen / Área'), ('vol_vol', 'Volumen / Volumen'), ('masa_area', 'Masa / Área'), ('masa_vol', 'Masa / Volumen'), ('unidades', 'Unidades')], default='vol_area', max_length=15)),
            ],
            options={
                'verbose_name': 'Unidad de medida',
                'verbose_name_plural': 'Unidades de medida',
                'ordering': ['tipo', 'codigo'],
            },
        ),
        migrations.AlterField(
            model_name='itemfitosanitario',
            name='dias_antes_cosecha',
            field=models.IntegerField(blank=True, null=True, verbose_name='Intervalo seguridad (días)'),
        ),
        migrations.AlterField(
            model_name='itemfitosanitario',
            name='condicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='campanas.condicion'),
        ),
        migrations.AlterField(
            model_name='plantillaproducto',
            name='condicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='campanas.condicion'),
        ),
        migrations.AlterField(
            model_name='itemfitosanitario',
            name='objetivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='campanas.objetivo'),
        ),
        migrations.AlterField(
            model_name='plantillaproducto',
            name='objetivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='campanas.objetivo'),
        ),
        migrations.AddField(
            model_name='objetivo',
            name='plaga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetivos', to='campanas.plaga'),
        ),
        migrations.AddField(
            model_name='itemfitosanitario',
            name='plaga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='campanas.plaga'),
        ),
        migrations.AddField(
            model_name='plantillaproducto',
            name='plaga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='campanas.plaga'),
        ),
        migrations.AlterField(
            model_name='itemfitosanitario',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='campanas.unidadmedida'),
        ),
        migrations.AlterField(
            model_name='plantillaproducto',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='campanas.unidadmedida'),
        ),
    ]
