# Generated by Django 6.0 on 2026-06-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanas', '0003_condicion_objetivo_plaga_unidadmedida_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemfitosanitario',
            options={'ordering': ['etapa', 'producto__nombre']},
        ),
        migrations.AlterModelOptions(
            name='laborcampana',
            options={'ordering': ['etapa', 'fecha_programada']},
        ),
        migrations.AlterModelOptions(
            name='plantillalabor',
            options={'ordering': ['etapa', 'semana_relativa', 'tipo_labor__nombre']},
        ),
        migrations.AlterModelOptions(
            name='plantillaproducto',
            options={'ordering': ['etapa', 'producto__nombre']},
        ),
        migrations.AddField(
            model_name='itemfitosanitario',
            name='etapa',
            field=models.CharField(blank=True, choices=[('preparacion', 'Preparación'), ('germinacion', 'Germinación'), ('crecimiento', 'Crecimiento'), ('establecido', 'Establecido'), ('poda', 'Poda'), ('brotacion', 'Brotación'), ('floracion', 'Floración'), ('cosecha', 'Cosecha')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='laborcampana',
            name='etapa',
            field=models.CharField(blank=True, choices=[('preparacion', 'Preparación'), ('germinacion', 'Germinación'), ('crecimiento', 'Crecimiento'), ('establecido', 'Establecido'), ('poda', 'Poda'), ('brotacion', 'Brotación'), ('floracion', 'Floración'), ('cosecha', 'Cosecha')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='plantillalabor',
            name='etapa',
            field=models.CharField(blank=True, choices=[('preparacion', 'Preparación'), ('germinacion', 'Germinación'), ('crecimiento', 'Crecimiento'), ('establecido', 'Establecido'), ('poda', 'Poda'), ('brotacion', 'Brotación'), ('floracion', 'Floración'), ('cosecha', 'Cosecha')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='plantillaproducto',
            name='etapa',
            field=models.CharField(blank=True, choices=[('preparacion', 'Preparación'), ('germinacion', 'Germinación'), ('crecimiento', 'Crecimiento'), ('establecido', 'Establecido'), ('poda', 'Poda'), ('brotacion', 'Brotación'), ('floracion', 'Floración'), ('cosecha', 'Cosecha')], default='', max_length=15),
        ),
    ]
