# Generated by Django 6.0 on 2026-06-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanas', '0006_campana_tipo_ciclo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoagricola',
            name='tipo',
            field=models.CharField(choices=[('enmienda', 'Enmienda orgánica'), ('biologico', 'Control biológico'), ('bioestimulante', 'Bioestimulante'), ('fertilizante', 'Fertilizante'), ('fitosanitario', 'Fitosanitario'), ('otro', 'Otro')], default='enmienda', max_length=20),
        ),
    ]
