# Generated by Django 6.0 on 2026-06-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanas', '0007_producto_tipo_organico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipolabor',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
