# Generated by Django 6.0 on 2026-06-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanas', '0008_tipolabor_codigo_autogenerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfitosanitario',
            name='estado',
            field=models.CharField(choices=[('programado', 'Programado'), ('aplicado', 'Aplicado')], default='programado', max_length=15),
        ),
        migrations.AddField(
            model_name='itemfitosanitario',
            name='fecha_aplicada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
