# Generated by Django 5.2.15 on 2026-06-04 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('insumos', 'Insumos'), ('agua', 'Agua'), ('semillas', 'Semillas'), ('mano_obra', 'Mano de obra'), ('herramientas', 'Herramientas'), ('otro', 'Otro')], max_length=20, verbose_name='Concepto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto (S/)')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='cultivos.cultivo', verbose_name='Cultivo')),
            ],
            options={
                'verbose_name': 'Costo de Producción',
                'verbose_name_plural': 'Costos de Producción',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PracticaSostenible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('compost', 'Uso de compost'), ('biol', 'Uso de biol'), ('sin_agroquimicos', 'Sin agroquímicos'), ('riego_eficiente', 'Riego eficiente'), ('mulching', 'Mulching'), ('control_biologico', 'Control biológico'), ('otro', 'Otro')], max_length=30, verbose_name='Tipo de práctica')),
                ('fecha', models.DateField(verbose_name='Fecha de aplicación')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción breve')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas', to='cultivos.cultivo', verbose_name='Cultivo')),
            ],
            options={
                'verbose_name': 'Práctica Sostenible',
                'verbose_name_plural': 'Prácticas Sostenibles',
                'ordering': ['-fecha'],
            },
        ),
    ]
