# Generated by Django 5.2.15 on 2026-06-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('riego', 'Riego'), ('fertilizacion', 'Fertilización orgánica'), ('control', 'Control preventivo'), ('cosecha', 'Cosecha'), ('rotacion', 'Rotación de cultivos'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de alerta')),
                ('fecha_programada', models.DateTimeField(verbose_name='Fecha y hora programada')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción o nota')),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='Prioridad')),
                ('completada', models.BooleanField(default=False, verbose_name='Completada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['completada', 'fecha_programada'],
            },
        ),
    ]
