# Generated by Django 5.2.15 on 2026-06-04 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alertas', '0001_initial'),
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='cultivos.cultivo', verbose_name='Cultivo'),
        ),
    ]
